env:
  global:
    - secure: BuRLhTwftzuJ3q/K9VZbnI/VxyH2jL3urI5inhKeZr3gF8MmJrBRwnrPjGH6CK25+ZpsE1ZTh91btQcMomKeDBKiSJF0RpqmE0fpqu58z+eBkV9mJ39skj9BRBAQPyqU6Wt5VWbflli1FsFLiq2yVXa18Vnq1D+j/O19PN9wP3+vzL0GfMZdsvIN8NU02F4uSefGq0EH5RJdwTf8J9fI486IbzGzC8kRFHVSwcCpMtM+FlYOQ3GdhrS/q1dTlYUvt0B3fgIZxw0BG+kRXe9+Gf1mfyU8me9nvHJZMnkPAtNIZt31setPTLuxfC0Qq7UEbl5u+rxhM8ElcT6WNF5MNJlhmNOOsjka+uM1dmXWnI4TP+cDOkQsbvrARQxHhsOW2/BsDjcWVvpnSvM7i+GvgjOFU3n/E0eCdivhaxhoOtCxX1t8M5JBhLoZR8F9XMIi71U4iEhbNteDBDXlQczndTdVLkiiwOMwUO0hNnXi8jA9bWHKJ6/6vRLYMh30Uc3JkrQnxCaIYh4cVhMjL6g04gvTYtMmM+J0Ivy1/CvML6Uz/NPVTLXDhOYOTxNBpDfBl2FUHz+WA1Hof1SvzDE2hnU7ygevIzpdNsdCctN39b6hk4U8huhl0K7j9ctfNx4DljoHO90/IHC36xoEZRM3Z3VYxaKHn50zazSeAgXhdDs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
