env:
  global:
    - secure: DlqmdmIM3if6RvCwugg6MKG4n2obONnE1hD7dxnOYCwDdOrNTWlosG/+tzWPGUzO51vm9NrbhKy1pGL7Y/a1rLY59KvtQTx8zr5HTfK3WJFzWbixVtPA+XbAoTp9vyaVLsBFVZ6/TF9I3GXpkgto0H3LtPp3l2ZS420UmAeP6Ak/9o7ZD8Z9y0/9/QJ/9MYg3iv7liv94oJam/BF9uk23oxHeCWsU9UHhLNSQuIHe0rFOBF3uOhBlRxJ08qQ8F83iwHi/ON8LqNOtbdiSa2gzYID6+RkBqRS60FbEuRcAeqBflAqxz5Iokjsy3jeY+vtHVX3IGYwQ65LrrRj6eesvRWJV88Zk9TwNL9vlqChbXNL/Vy6hZ15BDizYCXUc/TkrwdFzlTTFeLSzC1Sec0NPHoPxAvu96LVVXIzEtphITxj67BPNMLJuyiV7p25jZDSqFZN2dNV8J7yilfwAB/4W54o4MMSnBXxyx5a15AKecAXPH+13kf4ygVorjASVt0hWw078E8kAuydSI31PQr/5qR+RUIn/hHCXW5IWeszV2SAiwn96VDZF1q6QSiSO2b3KMXebgpB3kxQK3IiWNml4vicYCDQHh+AwIbBtJDdfacsTE8sW3UBkOCuxbwvQ+qnqNCvA3zZctyHQgbNbyXZD3Ezktg0Qf38VtFqOjbZWKk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
