env:
  global:
    - secure: FAZPoeE0AXqSTUgyMWWuVT45rzLJxQDUv2+E4bqNqjmIV+2CxCqCzTPg398LzCmKbiAAAmRSxCWCIjooejZ2rpF4j1SSkF3HXEat6DYrFKHoq7Qfth51S5P7sZyFXgsFjb7wSoYXj5syXKIBe30Ti10fMZdGvBdPVNgaGP0SWC5rjG6tUh8c3WScwgMQIK/u7u4iXjfVhRAXMuxuNHzPkBBWGiGn9D0qC0hX24LKsI69BASY8X6cFgaaFcRLWla5AcRmuEjn7sQXbFbXU//cccJFspjigXT9MqvS7vT4l8LnObBg01xiJswNrtMK0YT0m5l1Q+TCXtuyYlswQn0IP9VjfGe42hbcSZywB9InYq8pvdvVT2AbVlpMR/0BpDGU/ILQj70GNg8DkgnhsF8V226ME5WNd7cKHHvTDiiSFsNNfm5VjHu5QHzeG46P3haEvRkHefDb6B5oqfV/YRj7S2nb0pS/GvGGVj/bgjsmLZeGkVJGtycK7X8FLbsI3j04S06/XKOEaH4mxgOXpKZctzP0jCk9wg9wGIlD+XrO6f77JesqICpEFUtJ2vkoy1SpU1db0utpnRkOBRjUbGxStD6NZQB5qG4ke730PtujrjL5XYMgwkWcTqrGIxfBsV6/nhC/odL9C11O5zgark4FZEviWsXBDslkdKve3V5ew1E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
