env:
  global:
    - secure: bv6Lq7bZJ925bjIe7/N5KHgGRJYkqnzd1gB/ysoTg9jaRSHxg+n2EJh5R/8eZmANOhYJXPt/NpLeNpVtsnwDjo8jRDb+IKYkJ4M1DbnoFVl2vI3BN2PIq/H7/NZWy6UMnv8SLp9iiTd0Zpu3PFR1nIUpsJ2MGkk2SbCgvErAoZn1aIGOOCaU2s1urNsZmHxZ0FDFM7D8OW3aV8ipMRZXV8UuKTHklUGwvsN41ZOOsjeEFHUFK77dARt1ZgoMnvKb/e49Mjm4dLo/33Y3hNUHUpyhDHgn1IZgvDDaRmydaIHMHZBbyeQW0QrI/y+4oHP+K06kJg3cf2M654DTdGk5VLI7P0UlZrcC1Lf4pMb/Rj1RPuhH1FZLuEJoHutECbY2n+8pEmhviiSRw1o9BzwhoZn9r61IpmCKdBMCmN/PpsK47/Vfo1Totey4DLyUZWGPddcxwLNUq01JsXMwz8URB8AhSxsWaCThCcfBC6zJYy3/NsvHVE4YBHGNa51IB4VDfqQDhvRLHl3dk5CHB65uw1na8lWYuUHV81awWYkhuntX74pYTh0g/E219Ox4IRA0KP9Iy4VFoOOImdQenRb5Zmp0gdhiyGDZH4ZpVZnNSoCdZIb3lUe7VDNTOGd9RgqqgE7khxYDzOvhY9bYokfbsglh3SfhWNU4hogzW+hHYGM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
