env:
  global:
    - secure: IUwqXa+Ly4t21rt2G7B/1V3rxJRUagprJrx0HLra8bWl8u6r066URssyclw5B47ugXADsEdpq5sMPX3q5bXAnlQmEvkIhr9EunYzL7rc7aHcUByJrVcIUEEuyi/TNyFPDbgz9147ogjmPEAqcYuTRJKiE1cEHPzLjZ1BvgenlOfNQ7MIL6uVjUQP4mNPWeOH3kav7KlC7giECJZkng2ai7qtTvt3wMOvJMtZOO0rylgSvw6ZcnRwbkCHT92U0/jXXupLa+MQZ0JbNoagRadVobjj0jQ+G6/c6ylTBxhSQFWoow5/KPJ2L5FVLALyKZDZOV5Rx6m1ZRS4vt3S6NxIsjUX3wUxLsx3WiLfSUzCNqWVMHSK+OAf8KMac7uPoc3s3XAlie1iirIdpQ0AY3gPQaG056OSu8+9//2P+mJaotEvzmC+D6PAvnYxkeiGrg7KfDJDEFy+r51YcVINf7G2gHI4bxFJA1luoNklwDqaTiZHPyxnhbS0s965QCvrUy8/hwqMQt4J4fmhcBGO+ugmz5NJeZwpiRXhIFtjPcyQXkBXqhKe/yRSbfVddApAheKwem51fSn8szAeBMiZ+QhIytC7Z0/9Bca+U/q5+I8egU+XuKlv4fdf3lPppjdZylkv9VcsBREwcAMcDeAM97cNsJSzDZ0JGcwpU0sFg8Hf2q4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
